### ISSUE TITLE
Rename GFDL_fms to fms

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/MOM6#5]
I'm beginning the move from `@GFDL_fms` to `@fms` a la GEOS-ESM/MOM5#7. This should be done here at some point...though maybe not right now until @sdrabenh and I fix the current gcm

**Comment by mathomp4** [comment]
The FMS name change has been done in GEOS stable/develop, but I think for this to work, I'll need to do the same name change in the FMS repo itself on the `geos/master` branch. When you are ready for this, let me know and I can do it for you so that it will be correct for `fms_r8` in MOM6

**Comment by mathomp4** [comment]
Added issue GEOS-ESM/FMS#7

**Comment by aerorahul** [comment]
@mathomp4 Go ahead and edit the [CMakeLists.txt](https://github.com/GEOS-ESM/MOM6/blob/geos/CMakeLists.txt) to replace `GFDL_fms_r8` with `fms_r8` in the `MOM6::geos` branch and the corresponding FMS repo.

**Comment by sanAkel** [comment]
@mathomp4 @aerorahul I'm totally grounded to getting the interface into some shape (fskills and such). Is there anything I NEED TO DO? I'm not reading all above.
